### PR TITLE
Remove interface for cross-compat

### PR DESCRIPTION
**Pull request by jclausen**
The interface currently implemented is not cross-compatible between Coldbox 4 and 5.  The only way to ensure dependencies are stable between the two versions is to remove the interface implementation

### CODE REVIEW

**Comment by bdw429s** [comment]
These commits look to be part of the master branch already.  Can this pull be closed @jclausen?

**Comment by lmajano** [comment]
Why was this merged?

**Comment by jclausen** [comment]
Yes, Luis manually added these commits, so this PR should have been closed/declined.  Not sure why it was merged.

**Comment by bdw429s** [comment]
I didn't merge this pull.  I merged development into master to release a pull request from Tim Brown.  The reason that merge showed up on this pull was because this pull was a generic pull for dev to be merged to master so anything that happened to dev showed up on this pull.  

@jclausen I'm not sure what you mean by Luis manually adding commits. Your pull was from the dev branch on this repo so the commits were already _on_ development.  Where else would Luis add them to?  Surely not master!  Master should only be merged into from dev.

**Pull request merged**
